name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rohit714/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rohit714/react-test npm test

      - run: docker build -t rohit714/multi-client ./client
      - run: docker build -t rohit714/multi-nginx ./nginx
      - run: docker build -t rohit714/multi-server ./server
      - run: docker build -t rohit714/multi-worker ./worker

      - run: docker push rohit714/multi-client
      - run: docker push rohit714/multi-nginx
      - run: docker push rohit714/multi-server
      - run: docker push rohit714/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-916964668233
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
